version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "toolifelesstocode"
    labels:
      - "t: dependencies"
      - "t: backend"
