# Config file ~~stolen~~ borrowed from https://github.com/nextcord/nextcord

ci:
  autofix_commit_msg: |
    style: auto fixes from pre-commit hooks
repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        name: Running black in all files.
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black", "--extend-skip", "examples"]
